### PR TITLE
Cancelled Method Addition

### PR DESCRIPTION
**Pull request by tawtsvenz**

### CODE REVIEW

**Comment by tawtsvenz** [comment]
It would be convenient to have a way to check if a transaction was cancelled by customer not paying or customer having a refund done , so as to make any necessary changes to payment status in Java apps

**Comment by tzifudzi** [comment]
Please note the SDK has been updated to use Enums for the different types of transaction status.

**Comment by iammerus** [comment]
Structural changes like these should be propagated across the different SDKs. This ensures that we have a consistent API. Also the Paynow docs need to be updated to reflect the changes.  @tzifudzi, @webdevprojects-zw, how can we go about tracking these issues?

**Comment by tzifudzi** [comment]
@melmups you raise a good point that consistency should be maintained across the SDKs. I propose we have documentation that will list requirements that will be maintained across the SDKs. In the meantime I will revert some changes I had made to maintain as much consistency as possible.

In the future the tricky part will be that sometimes Java best practices or naming conventions may differ from say .NET and it will be trickier to maintain consistency there.

**Pull request merged**
